import { ref, computed } from 'vue'

// Estado global del idioma
const currentLanguage = ref<'es' | 'en'>('es')

// Traducciones
const translations = {
  es: {
    // Auth - Password recovery
    forgotTitle: 'Recuperar contraseña',
    forgotSubtitle: 'Ingresa tu correo electrónico y te enviaremos un código de 6 dígitos para restablecer tu contraseña.',
    codeExpiresInfo: 'El código expirará en 15 minutos. Si no ves el correo, revisa tu carpeta de spam.',
    sendCode: 'Enviar código',
    sendingCode: 'Enviando código...',
    backToLogin: 'Volver al inicio de sesión',
    codeSentTitle: 'Código enviado',
    codeSentDesc: 'Si el correo existe en nuestro sistema, recibirás un código de 6 dígitos. Revisa también tu carpeta de spam.',
    codeSendError: 'No se pudo enviar el código. Intenta nuevamente.',

    // Auth - Password reset with OTP
    resetTitle: 'Restablecer contraseña',
    resetSubtitle: 'Ingresa el código de 6 dígitos que enviamos a tu correo y tu nueva contraseña.',
    verificationCode: 'Código de verificación',
    codePlaceholder: '123456',
    enterSixDigitCode: 'Ingresa el código de 6 dígitos que recibiste por correo',
    codeMustBeSixDigits: 'El código debe tener 6 dígitos',
    newPasswordLabel: 'Nueva contraseña',
    confirmNewPassword: 'Confirmar nueva contraseña',
    attemptsLeftPrefix: 'Te quedan',
    attemptsLeftSuffix: 'intentos. Después tendrás que solicitar un nuevo código.',
    resetting: 'Restableciendo...',
    resetPassword: 'Restablecer contraseña',
    resending: 'Reenviando...',
    resendCode: 'Reenviar código',
    resendInPrefix: 'Reenviar código en',
    emailNotProvided: 'Email no especificado',
    passwordUpdatedTitle: '¡Contraseña actualizada!',
    passwordUpdatedDesc: 'Tu contraseña ha sido restablecida exitosamente. Ahora puedes iniciar sesión.',
    invalidCodeTitle: 'Código inválido',
    attemptsExceededDesc: 'Has excedido el número de intentos. Solicita un nuevo código.',
    invalidOrExpiredCode: 'Código inválido o expirado',
    codeResentTitle: 'Código reenviado',
    codeResentDesc: 'Se ha enviado un nuevo código a tu correo electrónico.',
    resendCodeError: 'No se pudo reenviar el código. Intenta nuevamente.',
    // Header
    searchPlaceholder: 'Buscar proyectos, organizaciones...',
    myProfile: 'Mi Perfil',
    logout: 'Cerrar Sesión',
    
    // Sidebar
    home: 'Inicio',
    projects: 'Proyectos',
    explore: 'Explorar',
    myApplications: 'Mis Postulaciones',
    organizations: 'Organizaciones',
    profile: 'Mi Perfil',
    messages: 'Mensajes',
    accessibility: 'Accesibilidad',
    darkMode: 'Modo oscuro',
    settings: 'Configuración',
    help: 'Ayuda',
    exit: 'Salir',
    
    // Dashboard
    greeting: '¡Hola',
    dashboardSubtitle: 'Aquí tienes un resumen de tu actividad y proyectos recomendados.',
    activeProjects: 'Proyectos Activos',
    hoursThisMonth: 'Horas este mes',
    achievements: 'Logros',
    recommendedProjects: 'Proyectos Recomendados',
    recentActivity: 'Actividad Reciente',
    viewDetails: 'Ver detalles',
    completedActivity: 'Completaste una actividad en',
    daysAgo: 'Hace',
    days: 'días',
    
    // Projects
    exploreProjects: 'Explorar Proyectos',
    projectsSubtitle: 'Encuentra proyectos de voluntariado que se ajusten a tus intereses',
    searchProjects: 'Buscar proyectos...',
  loadingProjects: 'Cargando proyectos...',
  projectsLoadError: 'No se pudieron cargar los proyectos. Por favor, intenta nuevamente.',
  noProjectsFound: 'No se encontraron proyectos',
  adjustFilters: 'Intenta ajustar los filtros de búsqueda para ver más resultados.',
  retry: 'Reintentar',
    allCategories: 'Todas las categorías',
    education: 'Educación',
    environment: 'Medio Ambiente',
    health: 'Salud',
    technology: 'Tecnología',
  newestTab: 'Nuevos',
  mostPopularTab: 'Más Populares',
  categorySocial: 'Social',
  categoryEducational: 'Educativo',
  categoryEnvironmental: 'Ambiental',
  durationOneMonth: '1 mes',
  durationTwoToThreeMonths: '2-3 meses',
  durationMoreThanThreeMonths: 'Más de 3 meses',
  moreThan100: 'Más de 100',
  thisWeek: 'Esta semana',
  thisMonth: 'Este mes',
  nextMonth: 'Próximo mes',
  slots: 'cupos',
    allLocations: 'Todas las ubicaciones',
    madrid: 'Madrid',
    barcelona: 'Barcelona',
    valencia: 'Valencia',
    remote: 'Remoto',
    newBadge: 'Nuevo',
    organization: 'Organización',
    flexible: 'Flexible',
    viewMore: 'Ver más',
    apply: 'Postularme',
    applicationSent: 'Inscripción enviada',
    previous: 'Anterior',
    next: 'Siguiente',
    
    // Accessibility
    accessibilityOptions: 'Opciones de accesibilidad',
    fontSize: 'Tamaño de fuente',
    highContrast: 'Alto contraste',
    reduceMotion: 'Reducir movimiento',
    resetSettings: 'Restablecer configuración',

    // Public landing
    platformName: 'Plataforma de Voluntariado Juvenil',
    heroTitle: '¡Bienvenido a la comunidad de voluntarios!',
    heroSubtitle: 'Únete a nosotros y haz la diferencia.',
    ctaRegister: 'Regístrate ahora',
    ctaBrowse: 'Buscar proyectos',
    newsAndUpdates: 'Novedades y Noticias',
    signIn: 'Entrar',
    terms: 'Política/Términos de uso',
    support: 'Soporte/Contacto',
    institutionalInfo: 'Información institucional',
    termsIntro: 'Lee nuestras políticas y términos de uso.',
    usage: 'Condiciones de Uso',
    privacy: 'Política de Privacidad',
    cookies: 'Política de Cookies',
    
    // Términos y Condiciones detallados
    conditionsTitle: 'Condiciones de Uso',
    conditionsPurpose: 'Propósito',
    conditionsPurposeDesc: 'La Plataforma tiene como objetivo conectar jóvenes con proyectos de voluntariado social, ambiental, educativo y comunitario en Ecuador. Su uso está destinado exclusivamente a fines no lucrativos.',
    conditionsRegistration: 'Registro y uso de cuenta',
    conditionsRegistrationDesc: 'Para participar en actividades o registrar proyectos, el usuario debe crear una cuenta con información veraz y actualizada. El usuario es responsable de mantener la confidencialidad de su contraseña y de todas las actividades realizadas con su cuenta. La Plataforma se reserva el derecho de suspender o eliminar cuentas que incumplan los términos establecidos o usen el servicio con fines fraudulentos o inapropiados.',
    conditionsUserResponsibility: 'Responsabilidad del usuario',
    conditionsUserResponsibilityDesc: 'Al usar la Plataforma, el usuario se compromete a:',
    conditionsPoint1: 'No utilizarla para difundir contenido ilegal, ofensivo o discriminatorio.',
    conditionsPoint2: 'No recopilar información de otros usuarios sin su consentimiento.',
    conditionsPoint3: 'Respetar las normas y valores del voluntariado: solidaridad, respeto, responsabilidad y compromiso.',
    conditionsLimitation: 'Limitación de responsabilidad',
    conditionsLimitationDesc: 'La Plataforma actúa únicamente como un punto de encuentro entre voluntarios y organizaciones. No se hace responsable por daños, pérdidas o conflictos que surjan entre las partes involucradas en una actividad de voluntariado.',
    
    // Política de Privacidad detallada
    privacyTitle: 'Política de Privacidad',
    privacyIntro: 'La Plataforma de Voluntariado Juvenil Ecuador respeta y protege la privacidad de todos sus usuarios. Toda la información personal que recopilemos será tratada conforme a la legislación ecuatoriana vigente, incluyendo la Ley Orgánica de Protección de Datos Personales (LOPDP).',
    privacyDataCollected: 'Datos recopilados',
    privacyDataCollectedDesc: 'Podemos recopilar la siguiente información:',
    privacyData1: 'Datos de identificación (nombre, correo electrónico, edad, ciudad, etc.)',
    privacyData2: 'Información relacionada con tus intereses o experiencia en voluntariado',
    privacyData3: 'Datos técnicos sobre tu dispositivo y navegación (IP, navegador, fecha y hora de acceso)',
    privacyUsage: 'Uso de la información',
    privacyUsageDesc: 'La información recopilada se utiliza exclusivamente para:',
    privacyUsage1: 'Gestionar tu registro y participación en actividades',
    privacyUsage2: 'Conectarte con oportunidades de voluntariado',
    privacyUsage3: 'Mejorar la experiencia y funcionamiento de la Plataforma',
    privacyUsage4: 'Enviar notificaciones o información relevante (si así lo autorizas)',
    privacyProtection: 'Protección y almacenamiento de datos',
    privacyProtectionDesc: 'Tus datos son almacenados en servidores seguros y solo accesibles por personal autorizado. No compartimos ni vendemos tu información personal a terceros sin tu consentimiento expreso, salvo obligación legal.',
    privacyRights: 'Derechos del usuario',
    privacyRightsDesc: 'De acuerdo con la ley ecuatoriana, tienes derecho a:',
    privacyRight1: 'Acceder, rectificar o eliminar tus datos personales',
    privacyRight2: 'Revocar tu consentimiento para el uso de tus datos',
    privacyRight3: 'Solicitar información sobre el tratamiento de tu información',
    privacyContact: 'Puedes ejercer estos derechos contactándonos a través del correo: soporte@voluntariado.ec',
    
    // Política de Cookies detallada
    cookiesTitle: 'Política de Cookies',
    cookiesIntro: 'La Plataforma utiliza cookies para mejorar tu experiencia de navegación y optimizar el funcionamiento del sitio.',
    cookiesDefinition: '¿Qué son las cookies?',
    cookiesDefinitionDesc: 'Las cookies son pequeños archivos que se almacenan en tu dispositivo cuando visitas un sitio web. Sirven para recordar tus preferencias, mejorar el rendimiento del sitio y analizar el tráfico de usuarios.',
    cookiesTypes: 'Tipos de cookies utilizadas',
    cookiesEssential: 'Cookies esenciales',
    cookiesEssentialDesc: 'Necesarias para el funcionamiento del sitio (inicio de sesión, seguridad, navegación).',
    cookiesAnalytics: 'Cookies de análisis',
    cookiesAnalyticsDesc: 'Permiten medir y analizar el uso del sitio (por ejemplo, Google Analytics).',
    cookiesPreferences: 'Cookies de preferencias',
    cookiesPreferencesDesc: 'Guardan tus configuraciones o idioma preferido.',
    cookiesControl: 'Control de cookies',
    cookiesControlDesc: 'Puedes aceptar, rechazar o eliminar las cookies desde la configuración de tu navegador. Ten en cuenta que algunas funciones del sitio podrían no funcionar correctamente si desactivas las cookies esenciales.',
    institutionalIntro: 'Conoce más sobre nuestra organización, nuestros valores y el impacto que buscamos generar.',
    mission: 'Misión',
    missionMain: 'Promover la participación activa de la juventud ecuatoriana en el desarrollo social, ambiental y cultural del país, conectando a jóvenes con iniciativas de voluntariado que generen un impacto positivo en sus comunidades.',
    missionSecondary: 'Buscamos fortalecer el liderazgo, la empatía y la conciencia social de cada voluntario, brindándoles una plataforma digital segura y accesible que facilite su vinculación con organizaciones y proyectos que compartan sus valores.',
    vision: 'Visión',
    visionMain: 'Ser la red digital de voluntariado juvenil más representativa de Ecuador, reconocida por impulsar la solidaridad, la innovación social y el compromiso ciudadano entre las nuevas generaciones.',
    visionSecondary: 'Aspiramos a construir una sociedad más justa, colaborativa y sostenible, donde cada joven tenga la oportunidad de contribuir activamente al bienestar común y al cumplimiento de los Objetivos de Desarrollo Sostenible (ODS).',
    values: 'Valores',
    valuesIntro: 'Nuestros valores guían cada acción y decisión dentro de la Plataforma:',
    valueSolidarity: 'Solidaridad',
    valueSolidarityDesc: 'Actuamos con empatía, ayudando a quienes más lo necesitan.',
    valueCommitment: 'Compromiso',
    valueCommitmentDesc: 'Cumplimos con responsabilidad nuestras tareas y acuerdos.',
    valueRespect: 'Respeto',
    valueRespectDesc: 'Valoramos la diversidad de ideas, culturas y formas de pensar.',
    valueTeamwork: 'Trabajo en equipo',
    valueTeamworkDesc: 'Creemos en la cooperación como base del cambio social.',
    valueTransparency: 'Transparencia',
    valueTransparencyDesc: 'Mantenemos una comunicación clara y honesta con todos los usuarios.',
    valueInnovation: 'Innovación',
    valueInnovationDesc: 'Promovemos el uso de la tecnología para impulsar soluciones sociales.',
    valueService: 'Servicio',
    valueServiceDesc: 'Ponemos nuestras habilidades al servicio del bien común.',
    contactIntro: '¿Tienes dudas o necesitas ayuda? Escríbenos.',
    name: 'Nombre',
    email: 'Correo',
    subject: 'Asunto',
    message: 'Mensaje',
    send: 'Enviar',
    contactInfo: 'Información de contacto',
    lorem: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in pulvinar nisl. Vivamus euismod, sapien non pulvinar feugiat, purus lacus feugiat orci, vitae bibendum dui augue sit amet turpis.',
    
    // Auth - Login
    welcomeBack: 'Bienvenido de vuelta',
    loginSubtitle: 'Accede a tu panel de voluntario u organización.',
    emailLabel: 'Correo Electrónico',
    emailPlaceholder: 'tu@email.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: 'Introduce tu contraseña',
    rememberMe: 'Recordar usuario',
    forgotPassword: '¿Olvidaste tu contraseña?',
    loginButton: 'Iniciar Sesión',
    loggingIn: 'Iniciando sesión...',
    noAccount: '¿No tienes una cuenta?',
    registerHere: 'Regístrate aquí.',
    
    // Auth - Register Volunteer
    createVolunteerAccount: 'Crea tu Cuenta de Voluntario',
    registerSubtitle: 'Empieza a generar un impacto en tu comunidad.',
    firstName: 'Nombre',
    firstNamePlaceholder: 'Ingresa tu nombre',
    lastName: 'Apellido',
    lastNamePlaceholder: 'Ingresa tu apellido',
    phone: 'Teléfono',
    phonePlaceholder: '+57 300 123 4567',
    institution: 'Institución Educativa',
    institutionPlaceholder: 'Universidad, Colegio, etc.',
    password: 'Contraseña',
    passwordMin: 'Mínimo 8 caracteres',
    confirmPassword: 'Confirmar Contraseña',
    confirmPasswordPlaceholder: 'Confirma tu contraseña',
    acceptTerms: 'Al registrarte, aceptas nuestros',
    termsOfService: 'Términos de Servicio',
    and: 'y',
    privacyPolicy: 'Política de Privacidad',
    registerButton: 'Registrarse',
    registering: 'Registrando...',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    signInLink: 'Inicia sesión',
    areYouOrganization: '¿Eres una organización?',
    registerAsOrganization: 'Registrarse como Organización',
    
    // Auth - Register Organization
    createOrgAccount: 'Registro de Organización',
    orgSubtitle: 'Crea proyectos y gestiona voluntarios.',
    orgName: 'Nombre de la Organización',
    orgNamePlaceholder: 'Nombre legal de la organización',
    orgType: 'Tipo de Organización',
    orgTypePlaceholder: 'Selecciona el tipo',
    ngo: 'ONG',
    foundation: 'Fundación',
    association: 'Asociación',
    cooperative: 'Cooperativa',
    other: 'Otro',
    taxId: 'NIT / Número de Identificación Tributaria',
    taxIdPlaceholder: '123456789-0',
    address: 'Dirección',
    addressPlaceholder: 'Dirección completa',
    city: 'Ciudad',
    cityPlaceholder: 'Ciudad',
    country: 'País',
    countryPlaceholder: 'País',
    website: 'Sitio Web',
    websitePlaceholder: 'https://www.ejemplo.com',
    representativeName: 'Nombre del Representante Legal',
    representativeNamePlaceholder: 'Nombre completo',
    representativeEmail: 'Correo del Representante',
    representativeEmailPlaceholder: 'representante@organizacion.com',
    representativePhone: 'Teléfono del Representante',
    representativePhonePlaceholder: '+57 300 123 4567',
    description: 'Descripción de la Organización',
    descriptionPlaceholder: 'Describe brevemente tu organización y su misión...',
    registerAsVolunteer: 'Registrarse como Voluntario',
    
    // Profile
    myProfileTitle: 'Mi Perfil',
    editPhoto: 'Editar foto',
    personalInfo: 'Información Personal',
    edit: 'Editar',
    save: 'Guardar Cambios',
    cancel: 'Cancelar',
    emailAddress: 'Correo Electrónico',
    phoneNumber: 'Teléfono',
    educationalInstitution: 'Institución Educativa',
    passwordField: 'Contraseña',
    passwordHint: 'Dejar en blanco para no cambiar',
    
    // Projects - Create
    createProject: 'Creación de Proyecto',
    backToList: 'Volver a la lista',
    saveDraft: 'Guardar Borrador',
    createNewProject: 'Crear un Nuevo Proyecto',
    step: 'Paso',
    of: 'de',
    projectName: 'Nombre del Proyecto',
    projectNamePlaceholder: 'Ej: Limpieza de Playas 2024',
    projectNameLabel: '¿Cómo se llama tu proyecto?',
    projectNameHelp: 'Elige un nombre descriptivo y atractivo',
    nextStep: 'Siguiente Paso',
    previousStep: 'Paso Anterior',
    projectDetails: 'Detalles del Proyecto',
    projectDescription: 'Descripción',
    projectDescriptionPlaceholder: 'Describe los objetivos, actividades y beneficios del proyecto...',
    projectCategory: 'Categoría',
    selectCategory: 'Selecciona una categoría',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Finalización',
    capacityAndSummary: 'Capacidad y Resumen',
    maxCapacity: 'Cupo Máximo de Voluntarios',
    capacityPlaceholder: 'Número de voluntarios',
    organizationId: 'ID de Organización',
    organizationIdPlaceholder: 'ID de tu organización',
    projectSummary: 'Resumen del Proyecto',
    category: 'Categoría',
    startDateLabel: 'Inicio',
    endDateLabel: 'Fin',
    editDetails: 'Editar Detalles',
    confirmCreate: 'Confirmar y Crear Proyecto',
    creating: 'Creando...',
    
    // Projects - List
    projectsList: 'Lista de Proyectos',
    createNewProjectBtn: 'Crear Nuevo Proyecto',
    noProjects: 'No hay proyectos disponibles',
    noProjectsDesc: 'Comienza creando tu primer proyecto de voluntariado.',
    filterByCategory: 'Filtrar por categoría',
    filterByStatus: 'Filtrar por estado',
    allStatuses: 'Todos los estados',
    active: 'Activo',
    completed: 'Completado',
    cancelled: 'Cancelado',
    planning: 'Planificación',
    inProgress: 'En Progreso',
    volunteers: 'voluntarios',
    viewProject: 'Ver Proyecto',
    
    // Projects - Detail
    projectDetail: 'Detalle del Proyecto',
    back: 'Volver',
    editProject: 'Editar Proyecto',
    deleteProject: 'Eliminar Proyecto',
    projectInfo: 'Información del Proyecto',
    status: 'Estado',
    capacity: 'Capacidad',
    duration: 'Duración',
    location: 'Ubicación',
    organizationLabel: 'Organización',
    enrolledVolunteers: 'Voluntarios Inscritos',
    noVolunteers: 'Aún no hay voluntarios inscritos',
    viewAttendance: 'Ver Asistencia',
    viewHours: 'Ver Horas',
    attendanceTitle: 'Mis Asistencias',
    attendanceSubtitle: 'Historial de asistencias e inasistencias',
    exportPdf: 'Exportar PDF',
    filterProject: 'Filtrar por proyecto',
    filterDay: 'Filtrar por día',
    filterWeek: 'Filtrar por semanas',
    presence: 'Asistencia',
    absence: 'Inasistencia',
    noAttendances: 'No hay registros de asistencia',
    
    // Validation errors
    fieldRequired: 'Este campo es requerido',
    invalidEmail: 'El formato del correo no es válido',
    invalidPhone: 'El formato del teléfono no es válido',
    passwordTooShort: 'La contraseña debe tener al menos 8 caracteres',
    passwordRequirements: 'La contraseña debe tener al menos 8 caracteres, incluir 1 número, 1 mayúscula, 1 minúscula y 1 carácter especial',
    passwordsMismatch: 'Las contraseñas no coinciden',
    mustAcceptTerms: 'Debes aceptar los términos y condiciones',
    
    // Messages
    successTitle: '¡Éxito!',
    errorTitle: 'Error',
    warningTitle: 'Advertencia',
    infoTitle: 'Información',
    loginSuccess: '¡Inicio de sesión exitoso!',
    welcome: 'Bienvenido',
    registerSuccess: '¡Registro exitoso! Ahora puedes iniciar sesión.',
    profileUpdated: 'Perfil actualizado correctamente',
    profileUpdateError: 'No se pudieron guardar los cambios. Intenta nuevamente.',
  photoEditSoon: 'La edición de foto estará disponible próximamente',
  noUserInfoFound: 'No se encontró la información del usuario',
    projectCreated: '¡Proyecto creado exitosamente!',
    projectCreateError: 'Ocurrió un error al crear el proyecto. Por favor, intenta nuevamente.',
    draftSaved: 'Borrador guardado exitosamente',
    draftSaveError: 'No se pudo guardar el borrador',
    draftFound: 'Se encontró un borrador guardado. ¿Deseas continuar desde donde lo dejaste?',
    confirmExit: '¿Deseas salir? Los cambios no guardados se perderán.',
    confirmDelete: '¿Estás seguro de que deseas eliminar este proyecto?',
    deleteSuccess: 'Proyecto eliminado exitosamente',
    deleteError: 'No se pudo eliminar el proyecto',
    
    // Hero Banner
    whyVolunteer: '¿Por qué ser voluntario?',
    socialImpact: 'Impacto Social',
    socialImpactDesc: 'Contribuye al desarrollo de tu comunidad',
    personalDevelopment: 'Desarrollo Personal',
    personalDevelopmentDesc: 'Adquiere nuevas habilidades y experiencia',
    networking: 'Networking',
    networkingDesc: 'Conoce personas con tus mismos valores',
    certification: 'Certificación',
    certificationDesc: 'Obtén reconocimiento por tu labor',
    
    // Registration Selector
    joinCommunity: 'Únete a Nuestra Comunidad',
    chooseAccountType: 'Elige el tipo de cuenta que mejor se adapte a ti y empieza a generar un impacto positivo',
    volunteer: 'Voluntario',
    volunteerDesc: 'Dona tu tiempo y habilidades para ayudar a organizaciones y proyectos sociales',
    findProjects: 'Encuentra proyectos que te apasionen',
    developSkills: 'Desarrolla nuevas habilidades',
    connectCommunity: 'Conecta con tu comunidad',
    getCertificates: 'Obtén certificados',
    registerAsVolunteerBtn: 'Registrarme como Voluntario',
    organizationTitle: 'Organización',
    organizationDesc: 'Busca voluntarios comprometidos para tus proyectos e iniciativas sociales',
    publishProjects: 'Publica y gestiona proyectos',
    findVolunteers: 'Encuentra voluntarios',
    expandImpact: 'Amplía tu impacto social',
    managementTools: 'Herramientas de gestión',
    registerAsOrgBtn: 'Registrarme como Organización',
    alreadyAccount: '¿Ya tienes una cuenta?',
    signInHere: 'Inicia sesión aquí',
    notSure: '¿No estás seguro qué tipo de cuenta elegir?',
    contactUs: 'Contáctanos',
    weWillHelp: 'y te ayudaremos',
    allRightsReserved: 'Todos los derechos reservados',
    
    // Sidebar expandible
    mainMenu: 'Principal',
    quickActions: 'Atajos Rápidos',
    accessibilityMenu: 'Accesibilidad',
    supportMenu: 'Soporte',
    currentPage: 'Estás en',
    openMenu: 'Abrir menú lateral',
    closeMenu: 'Cerrar menú lateral',
    increaseText: 'Aumentar texto',
    decreaseText: 'Reducir texto',
    highContrastMode: 'Alto contraste',
    screenReader: 'Lector de pantalla',
    screenReaderNotSupported: 'Tu navegador no soporta la funcionalidad de lector de pantalla.',
    emailSupport: 'Email soporte',
    callUs: 'Llamar',
    policies: 'Políticas',
    termsOfUse: 'Términos',
    
    // Footer mejorado
    supportAndContact: 'Soporte y Contacto',
    policiesAndTerms: 'Políticas y Términos',
    followUs: 'Síguenos',
    contactForm: 'Contáctanos',
    helpCenter: 'Centro de Ayuda',
    privacyPolicies: 'Políticas de Privacidad',
    cookiePolicy: 'Política de Cookies',
    dataSecurity: 'Seguridad de Datos',
    
    // Common
    yes: 'Sí',
    no: 'No',
    ok: 'Aceptar',
    close: 'Cerrar',
    loading: 'Cargando...',
    noData: 'No hay datos disponibles',
    error: 'Error',
    success: 'Éxito',
    warning: 'Advertencia',
    info: 'Información',
    actions: 'Acciones',
    details: 'Detalles',
    date: 'Fecha',
    time: 'Hora',
    from: 'Desde',
    to: 'Hasta',
    all: 'Todos',
    none: 'Ninguno',
    select: 'Seleccionar',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    export: 'Exportar',
    import: 'Importar',
    download: 'Descargar',
    upload: 'Subir',
    delete: 'Eliminar',
    update: 'Actualizar',
    create: 'Crear',
    submit: 'Enviar',
    reset: 'Restablecer',
    clear: 'Limpiar',
    
    // FAQ Section
    faqTitle: 'Preguntas Frecuentes',
    faqSubtitle: 'Encuentra respuestas a las preguntas más comunes sobre la plataforma',
    faqQuestion1: '¿Cómo me registro en la plataforma?',
    faqAnswer1: 'Puedes registrarte haciendo clic en el botón "Regístrate ahora" en la parte superior de la página. Necesitarás elegir entre registrarte como voluntario o como organización, completar tus datos personales y verificar tu correo electrónico.',
    faqQuestion2: '¿Qué tipos de proyectos puedo encontrar?',
    faqAnswer2: 'En la plataforma encontrarás proyectos de voluntariado en diferentes categorías: social, educativo, ambiental y tecnológico. Puedes filtrar por categoría, ubicación, duración y horario para encontrar proyectos que se ajusten a tus intereses y disponibilidad.',
    faqQuestion3: '¿Cómo me inscribo en un proyecto?',
    faqAnswer3: 'Una vez que encuentres un proyecto que te interese, haz clic en "Ver detalles" para obtener más información. Si el proyecto está disponible, podrás hacer clic en "Inscribirse" y completar el proceso de postulación. Recibirás una confirmación por correo electrónico.',
    faqQuestion4: '¿Necesito experiencia previa para participar?',
    faqAnswer4: 'No necesariamente. Muchos proyectos están abiertos a personas sin experiencia previa, mientras que otros pueden requerir habilidades específicas. Cada proyecto indica claramente los requisitos y habilidades deseadas en su descripción.',
    faqQuestion5: '¿Cómo obtengo certificados de mis horas de voluntariado?',
    faqAnswer5: 'Las organizaciones pueden registrar las horas que completas en cada proyecto. Una vez que alcances las horas requeridas, recibirás un certificado digital que puedes descargar desde tu perfil. Los certificados son reconocidos oficialmente.',
    faqQuestion6: '¿Puedo participar en más de un proyecto a la vez?',
    faqAnswer6: 'Sí, siempre que puedas cumplir con los compromisos de tiempo y responsabilidades de cada proyecto. Te recomendamos revisar bien los horarios y fechas para asegurarte de que puedes participar activamente en todos los proyectos en los que te inscribas.',
    faqQuestion7: '¿Qué pasa si no puedo continuar con un proyecto?',
    faqAnswer7: 'Si por alguna razón no puedes continuar participando en un proyecto, debes comunicarte con la organización lo antes posible. Ellos te ayudarán a gestionar tu salida. Es importante ser responsable y comunicar cambios en tu disponibilidad.',
    
    // Profile - Extra validation
    phoneDigitsOnly: 'El teléfono debe contener solo números',
    phoneExact10: 'El teléfono debe tener exactamente 10 dígitos',
    // Profile - Header
    defaultRole: 'Usuario',
    photoOf: 'Foto de',
  },
  en: {
    // Auth - Password recovery
    forgotTitle: 'Recover password',
    forgotSubtitle: 'Enter your email and we will send you a 6-digit code to reset your password.',
    codeExpiresInfo: 'The code will expire in 15 minutes. If you don\'t see the email, check your spam folder.',
    sendCode: 'Send code',
    sendingCode: 'Sending code...',
    backToLogin: 'Back to sign in',
    codeSentTitle: 'Code sent',
    codeSentDesc: 'If the email exists in our system, you will receive a 6-digit code. Please check your spam folder as well.',
    codeSendError: 'Could not send the code. Please try again.',

    // Auth - Password reset with OTP
    resetTitle: 'Reset password',
    resetSubtitle: 'Enter the 6-digit code we sent to your email and your new password.',
    verificationCode: 'Verification code',
    codePlaceholder: '123456',
    enterSixDigitCode: 'Enter the 6-digit code you received by email',
    codeMustBeSixDigits: 'The code must have 6 digits',
    newPasswordLabel: 'New password',
    confirmNewPassword: 'Confirm new password',
    attemptsLeftPrefix: 'You have',
    attemptsLeftSuffix: 'attempts left. You will need to request a new code afterward.',
    resetting: 'Resetting...',
    resetPassword: 'Reset password',
    resending: 'Resending...',
    resendCode: 'Resend code',
    resendInPrefix: 'Resend code in',
    emailNotProvided: 'Email not provided',
    passwordUpdatedTitle: 'Password updated!',
    passwordUpdatedDesc: 'Your password has been successfully reset. You can now sign in.',
    invalidCodeTitle: 'Invalid code',
    attemptsExceededDesc: 'You have exceeded the number of attempts. Please request a new code.',
    invalidOrExpiredCode: 'Invalid or expired code',
    codeResentTitle: 'Code resent',
    codeResentDesc: 'A new code has been sent to your email.',
    resendCodeError: 'Could not resend the code. Please try again.',
    // Header
    searchPlaceholder: 'Search projects, organizations...',
    myProfile: 'My Profile',
    logout: 'Log Out',
    
    // Sidebar
    home: 'Home',
    projects: 'Projects',
    explore: 'Explore',
    myApplications: 'My Applications',
    organizations: 'Organizations',
    profile: 'My Profile',
    messages: 'Messages',
    accessibility: 'Accessibility',
    darkMode: 'Dark mode',
    settings: 'Settings',
    help: 'Help',
    exit: 'Exit',
    
    // Dashboard
    greeting: 'Hello',
    dashboardSubtitle: 'Here is a summary of your activity and recommended projects.',
    activeProjects: 'Active Projects',
    hoursThisMonth: 'Hours this month',
    achievements: 'Achievements',
    recommendedProjects: 'Recommended Projects',
    recentActivity: 'Recent Activity',
    viewDetails: 'View details',
    completedActivity: 'You completed an activity in',
    daysAgo: '',
    days: 'days ago',
    
    // Projects
    exploreProjects: 'Explore Projects',
    projectsSubtitle: 'Find volunteer projects that match your interests',
    searchProjects: 'Search projects...',
  loadingProjects: 'Loading projects...',
  projectsLoadError: 'Projects could not be loaded. Please try again.',
  noProjectsFound: 'No projects found',
  adjustFilters: 'Try adjusting the search filters to see more results.',
  retry: 'Retry',
    allCategories: 'All categories',
    education: 'Education',
    environment: 'Environment',
    health: 'Health',
    technology: 'Technology',
  newestTab: 'Newest',
  mostPopularTab: 'Most Popular',
  categorySocial: 'Social',
  categoryEducational: 'Educational',
  categoryEnvironmental: 'Environmental',
  durationOneMonth: '1 month',
  durationTwoToThreeMonths: '2-3 months',
  durationMoreThanThreeMonths: 'More than 3 months',
  moreThan100: 'More than 100',
  thisWeek: 'This week',
  thisMonth: 'This month',
  nextMonth: 'Next month',
  slots: 'spots',
    allLocations: 'All locations',
    madrid: 'Madrid',
    barcelona: 'Barcelona',
    valencia: 'Valencia',
    remote: 'Remote',
    newBadge: 'New',
    organization: 'Organization',
    flexible: 'Flexible',
    viewMore: 'View more',
    apply: 'Apply',
    applicationSent: 'Application submitted',
    previous: 'Previous',
    next: 'Next',
    
    // Accessibility
    accessibilityOptions: 'Accessibility options',
    fontSize: 'Font size',
    highContrast: 'High contrast',
    reduceMotion: 'Reduce motion',
    resetSettings: 'Reset settings',

    // Public landing
    platformName: 'Youth Volunteering Platform',
    heroTitle: 'Welcome to the volunteer community!',
    heroSubtitle: 'Join us and make a difference.',
    ctaRegister: 'Register now',
    ctaBrowse: 'Browse projects',
    newsAndUpdates: 'News & Updates',
    signIn: 'Sign in',
    terms: 'Policy/Terms of use',
    support: 'Support/Contact',
    institutionalInfo: 'Institutional information',
    termsIntro: 'Read our policies and terms of use.',
    usage: 'Terms of use',
    privacy: 'Privacy',
    cookies: 'Cookies',
    institutionalIntro: 'Learn more about our organization, our values and the impact we seek to generate.',
    mission: '🎯 Mission',
    missionMain: 'Promote active participation of Ecuadorian youth in the social, environmental and cultural development of the country, connecting young people with volunteer initiatives that generate positive impact in their communities.',
    missionSecondary: 'We seek to strengthen the leadership, empathy and social awareness of each volunteer, providing them with a safe and accessible digital platform that facilitates their connection with organizations and projects that share their values.',
    vision: '🌅 Vision',
    visionMain: 'To be the most representative digital youth volunteering network in Ecuador, recognized for promoting solidarity, social innovation and civic commitment among new generations.',
    visionSecondary: 'We aspire to build a more just, collaborative and sustainable society, where each young person has the opportunity to actively contribute to the common good and the fulfillment of the Sustainable Development Goals (SDGs).',
    values: '💚 Values',
    valuesIntro: 'Our values guide every action and decision within the Platform:',
    valueSolidarity: 'Solidarity',
    valueSolidarityDesc: 'We act with empathy, helping those in greatest need.',
    valueCommitment: 'Commitment',
    valueCommitmentDesc: 'We fulfill our tasks and agreements with responsibility.',
    valueRespect: 'Respect',
    valueRespectDesc: 'We value the diversity of ideas, cultures and ways of thinking.',
    valueTeamwork: 'Teamwork',
    valueTeamworkDesc: 'We believe in cooperation as the basis for social change.',
    valueTransparency: 'Transparency',
    valueTransparencyDesc: 'We maintain clear and honest communication with all users.',
    valueInnovation: 'Innovation',
    valueInnovationDesc: 'We promote the use of technology to drive social solutions.',
    valueService: 'Service',
    valueServiceDesc: 'We put our skills at the service of the common good.',
    contactIntro: 'Have questions or need help? Contact us.',
    name: 'Name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    send: 'Send',
    contactInfo: 'Contact information',
    lorem: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in pulvinar nisl. Vivamus euismod, sapien non pulvinar feugiat, purus lacus feugiat orci, vitae bibendum dui augue sit amet turpis.',
    
    // Auth - Login
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Access your volunteer or organization dashboard.',
    emailLabel: 'Email Address',
    emailPlaceholder: 'your@email.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    loginButton: 'Sign In',
    loggingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    registerHere: 'Register here.',
    
    // Auth - Register Volunteer
    createVolunteerAccount: 'Create Your Volunteer Account',
    registerSubtitle: 'Start making an impact in your community.',
    firstName: 'First Name',
    firstNamePlaceholder: 'Enter your first name',
    lastName: 'Last Name',
    lastNamePlaceholder: 'Enter your last name',
    phone: 'Phone',
    phonePlaceholder: '+1 234 567 8900',
    institution: 'Educational Institution',
    institutionPlaceholder: 'University, School, etc.',
    password: 'Password',
    passwordMin: 'Minimum 8 characters',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    acceptTerms: 'By registering, you accept our',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    registerButton: 'Register',
    registering: 'Registering...',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    areYouOrganization: 'Are you an organization?',
    registerAsOrganization: 'Register as Organization',
    
    // Auth - Register Organization
    createOrgAccount: 'Organization Registration',
    orgSubtitle: 'Create projects and manage volunteers.',
    orgName: 'Organization Name',
    orgNamePlaceholder: 'Legal name of the organization',
    orgType: 'Organization Type',
    orgTypePlaceholder: 'Select type',
    ngo: 'NGO',
    foundation: 'Foundation',
    association: 'Association',
    cooperative: 'Cooperative',
    other: 'Other',
    taxId: 'Tax ID / Identification Number',
    taxIdPlaceholder: '123456789-0',
    address: 'Address',
    addressPlaceholder: 'Full address',
    city: 'City',
    cityPlaceholder: 'City',
    country: 'Country',
    countryPlaceholder: 'Country',
    website: 'Website',
    websitePlaceholder: 'https://www.example.com',
    representativeName: 'Legal Representative Name',
    representativeNamePlaceholder: 'Full name',
    representativeEmail: 'Representative Email',
    representativeEmailPlaceholder: 'representative@organization.com',
    representativePhone: 'Representative Phone',
    representativePhonePlaceholder: '+1 234 567 8900',
    description: 'Organization Description',
    descriptionPlaceholder: 'Briefly describe your organization and its mission...',
    registerAsVolunteer: 'Register as Volunteer',
    
    // Profile
    myProfileTitle: 'My Profile',
    editPhoto: 'Edit photo',
    personalInfo: 'Personal Information',
    edit: 'Edit',
    save: 'Save Changes',
    cancel: 'Cancel',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    educationalInstitution: 'Educational Institution',
    passwordField: 'Password',
    passwordHint: 'Leave blank to keep unchanged',
    
    // Projects - Create
    createProject: 'Project Creation',
    backToList: 'Back to list',
    saveDraft: 'Save Draft',
    createNewProject: 'Create a New Project',
    step: 'Step',
    of: 'of',
    projectName: 'Project Name',
    projectNamePlaceholder: 'E.g: Beach Cleanup 2024',
    projectNameLabel: "What's your project name?",
    projectNameHelp: 'Choose a descriptive and attractive name',
    nextStep: 'Next Step',
    previousStep: 'Previous Step',
    projectDetails: 'Project Details',
    projectDescription: 'Description',
    projectDescriptionPlaceholder: 'Describe the objectives, activities and benefits of the project...',
    projectCategory: 'Category',
    selectCategory: 'Select a category',
    startDate: 'Start Date',
    endDate: 'End Date',
    capacityAndSummary: 'Capacity and Summary',
    maxCapacity: 'Maximum Volunteer Capacity',
    capacityPlaceholder: 'Number of volunteers',
    organizationId: 'Organization ID',
    organizationIdPlaceholder: 'Your organization ID',
    projectSummary: 'Project Summary',
    category: 'Category',
    startDateLabel: 'Start',
    endDateLabel: 'End',
    editDetails: 'Edit Details',
    confirmCreate: 'Confirm and Create Project',
    creating: 'Creating...',
    
    // Projects - List
    projectsList: 'Projects List',
    createNewProjectBtn: 'Create New Project',
    noProjects: 'No projects available',
    noProjectsDesc: 'Start by creating your first volunteer project.',
    filterByCategory: 'Filter by category',
    filterByStatus: 'Filter by status',
    allStatuses: 'All statuses',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    planning: 'Planning',
    inProgress: 'In Progress',
    volunteers: 'volunteers',
    viewProject: 'View Project',
    
    // Projects - Detail
    projectDetail: 'Project Detail',
    back: 'Back',
    editProject: 'Edit Project',
    deleteProject: 'Delete Project',
    projectInfo: 'Project Information',
    status: 'Status',
    capacity: 'Capacity',
    duration: 'Duration',
    location: 'Location',
    organizationLabel: 'Organization',
    enrolledVolunteers: 'Enrolled Volunteers',
    noVolunteers: 'No volunteers enrolled yet',
    viewAttendance: 'View Attendance',
    viewHours: 'View Hours',
    attendanceTitle: 'My Attendances',
    attendanceSubtitle: 'Attendance and absence history',
    exportPdf: 'Export PDF',
    filterProject: 'Filter by project',
    filterDay: 'Filter by day',
    filterWeek: 'Filter by weeks',
    presence: 'Presence',
    absence: 'Absence',
    noAttendances: 'No attendance records',
    
    // Validation errors
    fieldRequired: 'This field is required',
    invalidEmail: 'Invalid email format',
    invalidPhone: 'Invalid phone format',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordRequirements: 'Password must have at least 8 characters, include 1 number, 1 uppercase, 1 lowercase and 1 special character',
    passwordsMismatch: 'Passwords do not match',
    mustAcceptTerms: 'You must accept the terms and conditions',
    
    // Messages
    successTitle: 'Success!',
    errorTitle: 'Error',
    warningTitle: 'Warning',
    infoTitle: 'Information',
    loginSuccess: 'Login successful!',
    welcome: 'Welcome',
    registerSuccess: 'Registration successful! You can now sign in.',
    profileUpdated: 'Profile updated successfully',
    profileUpdateError: 'Could not save changes. Please try again.',
  photoEditSoon: 'Photo editing will be available soon',
  noUserInfoFound: 'User information not found',
    projectCreated: 'Project created successfully!',
    projectCreateError: 'An error occurred while creating the project. Please try again.',
    draftSaved: 'Draft saved successfully',
    draftSaveError: 'Could not save draft',
    draftFound: 'A saved draft was found. Do you want to continue from where you left off?',
    confirmExit: 'Do you want to exit? Unsaved changes will be lost.',
    confirmDelete: 'Are you sure you want to delete this project?',
    deleteSuccess: 'Project deleted successfully',
    deleteError: 'Could not delete project',
    
    // Hero Banner
    whyVolunteer: 'Why volunteer?',
    socialImpact: 'Social Impact',
    socialImpactDesc: 'Contribute to your community development',
    personalDevelopment: 'Personal Development',
    personalDevelopmentDesc: 'Acquire new skills and experience',
    networking: 'Networking',
    networkingDesc: 'Meet people with your same values',
    certification: 'Certification',
    certificationDesc: 'Get recognition for your work',
    
    // Registration Selector
    joinCommunity: 'Join Our Community',
    chooseAccountType: 'Choose the account type that best suits you and start making a positive impact',
    volunteer: 'Volunteer',
    volunteerDesc: 'Donate your time and skills to help organizations and social projects',
    findProjects: 'Find projects you are passionate about',
    developSkills: 'Develop new skills',
    connectCommunity: 'Connect with your community',
    getCertificates: 'Get certificates',
    registerAsVolunteerBtn: 'Register as Volunteer',
    organizationTitle: 'Organization',
    organizationDesc: 'Find committed volunteers for your projects and social initiatives',
    publishProjects: 'Publish and manage projects',
    findVolunteers: 'Find volunteers',
    expandImpact: 'Expand your social impact',
    managementTools: 'Management tools',
    registerAsOrgBtn: 'Register as Organization',
    alreadyAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    notSure: "Not sure which account type to choose?",
    contactUs: 'Contact us',
    weWillHelp: 'and we will help you',
    allRightsReserved: 'All rights reserved',
    
    // Sidebar expandible
    mainMenu: 'Main',
    quickActions: 'Quick Actions',
    accessibilityMenu: 'Accessibility',
    supportMenu: 'Support',
    currentPage: 'You are in',
    openMenu: 'Open side menu',
    closeMenu: 'Close side menu',
    increaseText: 'Increase text',
    decreaseText: 'Decrease text',
    highContrastMode: 'High contrast',
    screenReader: 'Screen reader',
    screenReaderNotSupported: 'Your browser does not support the screen reader functionality.',
    emailSupport: 'Email support',
    callUs: 'Call us',
    policies: 'Policies',
    termsOfUse: 'Terms',
    
    // Footer mejorado
    supportAndContact: 'Support and Contact',
    policiesAndTerms: 'Policies and Terms',
    followUs: 'Follow Us',
    contactForm: 'Contact Us',
    helpCenter: 'Help Center',
    privacyPolicies: 'Privacy Policies',
    cookiePolicy: 'Cookie Policy',
    dataSecurity: 'Data Security',
    
    // Common
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    actions: 'Actions',
    details: 'Details',
    date: 'Date',
    time: 'Time',
    from: 'From',
    to: 'To',
    all: 'All',
    none: 'None',
    select: 'Select',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    export: 'Export',
    import: 'Import',
    download: 'Download',
    upload: 'Upload',
    delete: 'Delete',
    update: 'Update',
    create: 'Create',
    submit: 'Submit',
    reset: 'Reset',
    clear: 'Clear',
    
    // FAQ Section
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Find answers to the most common questions about the platform',
    faqQuestion1: 'How do I register on the platform?',
    faqAnswer1: 'You can register by clicking the "Register now" button at the top of the page. You will need to choose between registering as a volunteer or as an organization, complete your personal information, and verify your email address.',
    faqQuestion2: 'What types of projects can I find?',
    faqAnswer2: 'On the platform you will find volunteer projects in different categories: social, educational, environmental, and technological. You can filter by category, location, duration, and schedule to find projects that match your interests and availability.',
    faqQuestion3: 'How do I enroll in a project?',
    faqAnswer3: 'Once you find a project that interests you, click on "View details" to get more information. If the project is available, you can click "Apply" and complete the application process. You will receive a confirmation email.',
    faqQuestion4: 'Do I need previous experience to participate?',
    faqAnswer4: 'Not necessarily. Many projects are open to people without previous experience, while others may require specific skills. Each project clearly indicates the requirements and desired skills in its description.',
    faqQuestion5: 'How do I get certificates for my volunteer hours?',
    faqAnswer5: 'Organizations can register the hours you complete in each project. Once you reach the required hours, you will receive a digital certificate that you can download from your profile. Certificates are officially recognized.',
    faqQuestion6: 'Can I participate in more than one project at a time?',
    faqAnswer6: 'Yes, as long as you can meet the time commitments and responsibilities of each project. We recommend reviewing schedules and dates carefully to ensure you can actively participate in all projects you enroll in.',
    faqQuestion7: 'What happens if I cannot continue with a project?',
    faqAnswer7: 'If for some reason you cannot continue participating in a project, you should contact the organization as soon as possible. They will help you manage your exit. It is important to be responsible and communicate changes in your availability.',
    
    // Profile - Extra validation
    phoneDigitsOnly: 'Phone number must contain digits only',
    phoneExact10: 'Phone number must be exactly 10 digits',
    // Profile - Header
    defaultRole: 'User',
    photoOf: 'Photo of',
  }
}

export function useLanguage() {
  // Inicializar idioma desde localStorage
  const savedLanguage = localStorage.getItem('language') as 'es' | 'en' | null
  if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'en')) {
    currentLanguage.value = savedLanguage
    document.documentElement.setAttribute('lang', savedLanguage)
  }

  const t = computed(() => translations[currentLanguage.value])

  const changeLanguage = (lang: 'es' | 'en') => {
    currentLanguage.value = lang
    localStorage.setItem('language', lang)
    document.documentElement.setAttribute('lang', lang)
  }

  return {
    currentLanguage,
    t,
    changeLanguage
  }
}
